### ISSUE TITLE
Errors in Visual Studio editor

### ISSUE THREAD

**Issue by kozera2137** [wbenny/hvpp#2]
Hi. I noticed that Visual Studio shows in editor a lot of errors but it compiles fine. I don't have this problem with other projects. Reinstalling VS, WDK etc. doesn't give any results. Is it a problem with the whole project or my setup? I'm using the newest VS 2017 Community and the newest WDK

**Comment by wbenny** [comment]
Hi! Yes, unfortunatelly, I have the same problem and had to "resolve" it via `Tools -> Options -> Text Editor -> C/C++ -> Advanced -> [Intellisense] Disable Squiggles`. My go-to explanation would be that it's because _C++ is not supported by Microsoft in Windows Driver development_, but that's rather lame. Maybe discrepancies in include paths? I have to admit I didn't investigate this issue deep enough yet, so if by any chance you or someone else happen to resolve it before I do, don't hesitate to share how did you achieve that. :)

**Comment by wbenny** [comment]
Although, judging by squiggles under `noexcept` keywords, it really looks like when Visual Studio project's toolset is set to `WindowsKernelModeDriver*`, it all breaks. Like it couldn't uderstand it should parse C++17 code.

**Comment by rianquinn** [comment]
I know that @tandasat had some C++ code compiling in the driver with HyperPlatform at one point, although I'm not sure if he had the same squiggle issue. Might be worth looking at though.

**Comment by tandasat** [comment]
I do not think I had the same issue in HyperPlatform, probably because I did not use much C++ specific constructs, and also did not use any of C++17 specific things. 

I did had the same issue in the other project though. In my case, removing all `noexcept` essentially addressed the issue (also, probably because codebase was more like C++03), but if you are using STL headers that's not possible to do.

**Comment by wbenny** [comment]
I've filled bug to VS Developer Community: https://developercommunity.visualstudio.com/content/problem/321040/intellisense-cannot-understand-c17-when-platform-t.html

**Comment by DragonQuestHero** [comment]
same problem!

**Comment by wbenny** [comment]
Resolved in recent VS2019 update.
