### ISSUE TITLE
About DebugBuggin

### ISSUE THREAD

**Issue by ghost** [wbenny/hvpp#22]
@wbenny Thought you should be aware that the user DebugBuggin who has been pestering you for help over the past few weeks is a Walmart game cheat author who pastes anything he can get his hands on and is taking credit for your work himself. You probably already noticed there was something wrong with him from his entitled attitude though.

![kscsbab](https://user-images.githubusercontent.com/39099239/49698081-e1a07400-fb73-11e8-9dcb-4ffc66f09c59.png)

**Comment by wbenny** [comment]
I'm fully aware and watching this funny show in the corner. :)

**Comment by rianquinn** [comment]
@nofvcks out of curiosity, where did you see this?

**Comment by ghost** [comment]
@rianquinn He was my former coding "partner." We used to cheat on a game called Rust, had a falling out and went our separate ways. I moved on to real work while he preferred to scam teenagers for their lunch money with pasted, detected cheat software for two years. I recognized his name immediately when I saw him posting questions, and all doubt was removed when he posted his email address in one of the questions. I chose not to say anything, but I recently (last night) exposed his fraudulent business to his customers and he is having a meltdown and trying to personally attack me on every platform he can think of, so I found it proper to post the truth about him here also. The chat screenshot is from one of his (many) disgruntled customers on a RocketChat server. Unfortunately, I don't have the actual server details. Though I have plenty of other hilarious screen captures of him saying absolutely nonsensical things if you want some good laughs.

**Comment by SmallHandsThug** [comment]
@wbenny I wouldn't entertain any of this to be honest. What you're dealing with is people who were banned from a service because they couldn't follow basic rules. Their "leader" this thuglife guy(nofvcks) who posted above is a middle aged man who lives at home with his parents, scams old people with malware+adware, abuses animals, and who suffers from severe depression so spends his time posting lies on the internet. He's upset with me because I posted his amateur code on a github(check my profile for the link) after he had a mental breakdown and started harassing me recently after a year. He and the 15 year old kids that follow him(who were also banned), are trying desperately to get hypervisors in-general detected and features of a game mod patched.
